### ISSUE TITLE
Probar con esto para ejecutar los test de selenium

### ISSUE THREAD

**Issue by DatFerPa** [Arquisoft/dashboard1a#1]
http://stackoverflow.com/questions/30643006/how-can-i-run-my-selenium-tests-with-maven

**Comment by DatFerPa** [comment]
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-failsafe-plugin</artifactId>
    <version>2.12</version>
    <executions>
        <execution>
            <id>default</id>
            <goals>
                <goal>integration-test</goal>
                <goal>verify</goal>
            </goals>
        </execution>
    </executions>
</plugin>

**Comment by martinp95** [comment]
https://vorba.ch/2016/integration-testing-spring-boot-travis-saucelabs.html

**Comment by DatFerPa** [comment]
Para ejecutar test de selenium:

1. iniciar aplicacion con : mvn spring-boot:run

2. Abrir otra consola y poner: mvn integration-test

PD: Utilizar firefox portable (Vale el de SDI, a poder ser).
